import * as fs from 'fs';
import * as path from 'path';
import Database from 'better-sqlite3';
import { openDatabase } from '../db/schema';
import { getRank, getModules, getStats, getFileMapCompact } from '../query/engine';

const MARKER_START = '<!-- claude-ex:start -->';
const MARKER_END = '<!-- claude-ex:end -->';

export function generateClaudeMd(rootDir: string, db?: Database.Database): string {
    const shouldClose = !db;
    if (!db) db = openDatabase(rootDir);

    try {
        const stats = getStats(db);
        const topSymbols = getRank(db, 15);
        const modules = getModules(db);
        const dirname = path.basename(rootDir);

        // Language breakdown
        const langs = db.prepare(`
            SELECT language, COUNT(*) as cnt FROM files WHERE language IS NOT NULL GROUP BY language ORDER BY cnt DESC
        `).all() as { language: string; cnt: number }[];

        const lines: string[] = [];
        lines.push(MARKER_START);
        lines.push(`# Project: ${dirname}`);
        lines.push('');
        lines.push('## Architecture');
        lines.push(`- **Languages**: ${langs.map(l => `${l.language} (${l.cnt} files)`).join(', ')}`);
        lines.push(`- **Size**: ${stats.files} files, ${stats.symbols} symbols, ${stats.edges} relationships`);
        lines.push('');

        if (topSymbols.length > 0) {
            lines.push('## Key Symbols (by structural importance)');
            for (let i = 0; i < topSymbols.length; i++) {
                const sym = topSymbols[i];
                lines.push(`${i + 1}. \`${sym.qualifiedName || sym.name}\` [${sym.kind}] in ${sym.file}`);
            }
            lines.push('');
        }

        if (modules.length > 0) {
            lines.push('## Module Map');
            for (const mod of modules.slice(0, 15)) {
                const imports = mod.importsFrom.length > 0
                    ? ` \u2192 imports from: ${mod.importsFrom.join(', ')}`
                    : ' \u2192 imports from: (none \u2014 leaf dependency)';
                lines.push(`${mod.name}/ (${mod.fileCount} files, ${mod.symbolCount} symbols)${imports}`);
            }
            lines.push('');
        }

        // File map — "where everything lives"
        const fileMap = getFileMapCompact(db);
        if (fileMap) {
            lines.push('## File Map (file → key exports)');
            lines.push('');
            lines.push(fileMap);
            lines.push('');
        }

        lines.push('## Codex MCP Tools — USE THESE');
        lines.push('');
        lines.push('This project has a live code index via MCP. **Always prefer these over grep/ripgrep for structural queries.** They are faster, rank-aware, and understand code relationships.');
        lines.push('');
        lines.push('| Tool | Use for |');
        lines.push('|------|---------|');
        lines.push('| `search_code` | Finding symbols by name or description (PageRank-weighted) |');
        lines.push('| `find_files` | Finding files by name/path pattern (glob-style, e.g. `**/*.test.ts`) |');
        lines.push('| `get_file_map` | Complete project map — every file and its exports (the "memory") |');
        lines.push('| `get_symbol` | Full context for a symbol before modifying it |');
        lines.push('| `get_callers` | Who calls a function — use before renaming/removing |');
        lines.push('| `get_dependents` | What files break if a file changes |');
        lines.push('| `get_dependencies` | What a symbol imports/uses |');
        lines.push('| `get_file_symbols` | All symbols in a file (not just exports) |');
        lines.push('| `find_by_kind` | Find all classes, interfaces, enums, etc. |');
        lines.push('| `get_type_hierarchy` | Who extends/implements a class or interface |');
        lines.push('| `find_dead_exports` | Exported symbols nothing imports (dead code) |');
        lines.push('| `get_pkg_usages` | What files import from a given npm/pip package |');
        lines.push('| `get_architecture` | Project overview, top symbols, module map |');
        lines.push('| `reindex_file` | Re-index a file after major changes |');
        lines.push('| `review_diff` | Graph-aware diff review context (changed symbols, impact, risks) |');
        lines.push('');
        lines.push('**Workflow tips:**');
        lines.push('- Before editing a function: `get_symbol` + `get_callers` to understand impact');
        lines.push('- Before refactoring a file: `get_dependents` to know what breaks');
        lines.push('- To find code: `search_code` first (structural), fall back to grep only for literal strings/regex');
        lines.push('- To find files: `find_files` with glob patterns (faster than shell find/ls)');
        lines.push('- After large changes: `reindex_file` to keep the index fresh');
        lines.push('- Before reviewing a PR: `review_diff` with "branch" for full graph context');
        lines.push('');
        lines.push('*Auto-generated by claude-ex. Run `claude-ex generate-docs` to regenerate.*');
        lines.push(MARKER_END);

        return lines.join('\n');
    } finally {
        if (shouldClose) db.close();
    }
}

export function writeClaudeMd(rootDir: string, db?: Database.Database): void {
    const content = generateClaudeMd(rootDir, db);
    const claudeMdPath = path.join(rootDir, 'CLAUDE.md');

    if (fs.existsSync(claudeMdPath)) {
        const existing = fs.readFileSync(claudeMdPath, 'utf-8');

        if (existing.includes(MARKER_START) && existing.includes(MARKER_END)) {
            // Replace existing section
            const before = existing.slice(0, existing.indexOf(MARKER_START));
            const after = existing.slice(existing.indexOf(MARKER_END) + MARKER_END.length);
            fs.writeFileSync(claudeMdPath, before + content + after);
        } else {
            // Append
            fs.writeFileSync(claudeMdPath, existing.trimEnd() + '\n\n' + content + '\n');
        }
    } else {
        fs.writeFileSync(claudeMdPath, content + '\n');
    }
}
